### ISSUE TITLE
MLSD (parseRFC3659ListLine) parse issues

### ISSUE THREAD

**Issue by us3r64** [jlaffaye/ftp#107]
Treating `cdir`, `pdir` as `EntryTypeFolder` in parseRFC3659ListLine:
https://github.com/jlaffaye/ftp/blob/master/parse.go#L55

is losing the `meaning` of those two.

`cdir` - current directory (most of the time `.` but some servers can respond with the actual name)
```Type=cdir;Modify=20171007193955;UNIX.mode=0755; /```

`pdir` - parent directory ( most of the time `..` but some servers can respond with the actual name)
```Type=cdir;Modify=20171003145711;UNIX.mode=0755; /languages```
```Type=pdir;Modify=20171007193955;UNIX.mode=0755; /```

This can add issues with code trying to recursively read directories.
Also with `RemoveDirRecur`, going into an infinite loop
https://github.com/jlaffaye/ftp/blob/master/ftp.go#L512

**Comment by corny** [comment]
Would it solve this issue to ignore folders with name `/` as well?
