### ISSUE TITLE
feature request: add method to NetConn to return underlying net.Conn (or *net.TCPConn)

### ISSUE THREAD

**Issue by twmb** [jlaffaye/ftp#118]
Currently, there is no way to control deadlines on the underlying net connection. However, the `net.Conn` is the first thing created in `DialTimeout`. The concept of this `net.Conn` is lost once passed to `textproto.NewConn`.

Would you be receptive to the `tconn` being added as a struct field (say, `netconn`) on `ServerConn`? And then this method being added:

```go
func (c *ServerConn) NetConn() net.Conn {
        return c.netconn
}
```
?

This method can come with a strong disclaimer to not write / read from the connection itself, but it would allow users to control deadlines and see the connection's local and remote addresses.

**Comment by corny** [comment]
Another approach is to add a `func DialConn(conn *TCPConn) (*ServerConn, error) { ...`.

**Comment by jlaffaye** [comment]
You can now Dial with conn or dialer
