### ISSUE TITLE
ServerConn timeout how to set ?

### ISSUE THREAD

**Issue by jonnywang** [jlaffaye/ftp#122]
ServerConn  timeout how to set ?

**Comment by jonnywang** [comment]
```
func (c *ServerConn) Stor(path string, r io.Reader) error
```

**Comment by l-we** [comment]
> 你是说为初始化连接到ftp服务器设置超时？
> 我使用`DialTimeout()`并添加持续时间。
> 例如：
> `ftp.DialTimeout("172.22.227.127:21", 10*time.Second)`
> 这意味着在10秒后，尝试连接将停止。

failed

**Comment by jlaffaye** [comment]
Duplicate of https://github.com/jlaffaye/ftp/issues/167
