### ISSUE TITLE
Blocking at DialTimeout() -> time.Second*5 : FTP runnning at localhost:20

### ISSUE THREAD

**Issue by SreeshaKS** [jlaffaye/ftp#132]
The code is blocking at DialTimeout - with a timeout of time.Second*5; The connection never goes through nor does it return with an error

**Comment by jlaffaye** [comment]
Do you have some actionnable data ?
Like a tcpdump capture.

**Comment by l-we** [comment]
Such as the SFTP server connection

**Comment by phoenix147** [comment]
Same problem here, DialTimeout does not work. I will try to get a tcpdump next time.

This seems somehow related to
https://github.com/jlaffaye/ftp/issues/147
https://github.com/jlaffaye/ftp/issues/112

**Comment by jlaffaye** [comment]
Duplicate
