### ISSUE TITLE
229 Entering Extended Passive Mode

### ISSUE THREAD

**Issue by hippper** [jlaffaye/ftp#133]
I am getting an error "229 Entering Extended Passive Mode".
I tried not to use "EPSV mode", code like test case
If disableEPSV {
// delete(c.features, "EPSV")
c.DisableEPSV = true
}
However, after this operation, a connection timeout error occurs. Is this because the delete(c.features, "EPSV") is blocked in the code?
But the features attribute of object c, we are not accessible externally, so is there a defect here?

**Comment by jlaffaye** [comment]
You can use https://godoc.org/github.com/jlaffaye/ftp#DialWithDisabledEPSV
