### ISSUE TITLE
Wanting RetrFrom to return Status Code and message

### ISSUE THREAD

**Issue by ghilde** [jlaffaye/ftp#137]
In StorFrom() you have this line

`_, _, err := c.conn.ReadResponse(StatusClosingDataConnection)`

which if I modify to

`code, msg, err := c.conn.ReadResponse(StatusClosingDataConnection)`

then update return variables I can get the FTP status after running a STOR command. All good, and works fine with other commands too (MKD, RMD, etc). When I try to do a similar thing in RetrFrom() adding the same line and updating return variables, RETR hangs. FTP server initially logs status 150 (about to send file), then status 426 (connection timeout) 2 minutes later.

I see EPSV mode working, I see the TCP port in ESTABLISHED state, and after an initial flurry of FTP data packets, I receive nothing further and the connection is eventually dropped by FTP server (FileZilla FTP server).

Comment out the lines or return to current code and RETR works fine, just no status codes/messages.

Any ideas how to get statuses working for RETR? Thanks in advance

**Comment by jlaffaye** [comment]
Do you have a public FTP server I can play with ?

**Comment by jlaffaye** [comment]
What are you trying to achieve ?

**Comment by ghilde** [comment]
I'm trying to get all the statuses from the FTP server. Normally (at least, with Filezilla FTP Server) it gives status code 150 then 226 upon successful upload. If I could receive 226 after a STOR that would be ideal, I don't need the code 150. I know that if no error is thrown I can assume a successful upload and statically write one in my code, but would prefer to receive it officially from the FTP server.

**Comment by jlaffaye** [comment]
Well if you have no error when closing the io.Writer then the upload is succesful.

**Comment by ghilde** [comment]
By error, you mean FTP error code as well as other interworking error (network disconnection between user and host which would cause a transfer error but wouldn't result in an FTP server error code, for example)?

Just to clarify - FTP error codes include both 4xx and 5xx responses?

I know there's FTP code 350 (file action that requires further information), so would this be thrown as an error?
