### ISSUE TITLE
Unable to connect on windows

### ISSUE THREAD

**Issue by lyb-Q** [jlaffaye/ftp#142]
Unable to connect to ftp server on windows running program

 wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by xwbz2017** [comment]
I also encountered the same problem. After I commented out ftp.go:131, the problem was solved.

**Comment by xwbz2017** [comment]
It seems that the ftp server does not support the feat command.

**Comment by flazx** [comment]
+1 encountered the problem under window10.

**Comment by jlaffaye** [comment]
no actionable data.
