### ISSUE TITLE
Unable to parse files with ACL

### ISSUE THREAD

**Issue by g-rad** [jlaffaye/ftp#145]
Line with ACL permissions can not be parsed.

Example:
```
-rwxrw-r--+  1 521      101         2080 May 21 10:53 CUSG_2000026054.csv.gz
```

Here `-rwxrw-r--+` has 11 bytes with extra "+" at the end. Since it doesn't match any of parsers, the file stays ignored and hence invisible for the outer code.

Can we allow 11 bytes for the first field?

**Comment by g-rad** [comment]
Thank you for such quick response!

**Comment by corny** [comment]
You're welcome :wink:
