### ISSUE TITLE
Ftp server does not support "feat" command

### ISSUE THREAD

**Issue by xwbz2017** [jlaffaye/ftp#150]
**Describe the bug**
ftp服务器不支持“feat”指令导致拨号错误
Ftp server does not support "feat" command causing dialing error: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**To Reproduce**
```
	c, err := ftp.Dial("218.244.131.134:21", ftp.DialWithTimeout(1*time.Hour), ftp.DialWithDebugOutput(os.Stderr))
	if err != nil {
		log.Panic(err)
	}
	defer c.Quit()
```

**Expected behavior**
拨号成功
Dial succcess

**FTP server**
- FileZilla Server version 0.9.41 beta:
- 21 8 .24 4.13 1.13 4:21

**Debug output**
```
220-FileZilla Server version 0.9.41 beta
220-written by Tim Kosse (Tim.Kosse@gmx.de)
220 Please visit http://sourceforge.net/projects/filezilla/
FEAT
QUIT
2019/06/08 09:45:44 read tcp 192.168.0.104:50402->2 18.2 4 4.13 1.1 34 :21: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

**Additional context**
当我注释掉"ftp.go:131"就不会出现这个错误
This error does not occur when I comment out "ftp.go:131"

**Comment by corny** [comment]
If the server does not support `FEAT`, it has to respond with `502 Command not implemented`.
Is FileZilla Server really that broken?

**Comment by xwbz2017** [comment]
@corny Thanks, I just tried to connect to this address using the FileZilla FTP Client. It lost the connection when using the "AUTH TLS" command, which seems to be a problem with the server.
It may be that the server has set some strange restrictions.
