### ISSUE TITLE
Connecting over ssh tunnel

### ISSUE THREAD

**Issue by xoac** [jlaffaye/ftp#160]
Hi,

I wanted to connect through ssh tunnel but it look like I need to add some settings?
The strange things is that function `Stor()` did't work but for example `CurrentDir()` worked correctly. 

To reproduce you need server ftp on remote machine. You create a ssh tunel with `ssh -L 8021:127.0.0.1:21 user@remote-machine`
Where:
- `8021` is your new port from data will be transfered to `remote-machine` to addr `127.0.0.1:21`.

Now you should be able to connect to ftp server on localhost with port 8021. `CurrentDir()` should working but `Stor()` not.

In my case I used Mikrotik inner ftp server to copy file and I want to secure it with ssh tunnel.

**Comment by jlaffaye** [comment]
Well this is because the data is transferred on a new connection on another port.

**Comment by xoac** [comment]
Do you know a way to workaround?
