### ISSUE TITLE
STARTTLS support

### ISSUE THREAD

**Issue by dswarbrick** [jlaffaye/ftp#162]
I would like to be able to use this package with a Proftpd server, configured for explicit FTPS (i.e. STARTTLS). As far I can see, this package only supports implicit FTPS (e.g. port 990).

I've tried to work around this shortcoming with `DialWithNetConn` or `DialWithDialFunc`, which allow me to do the necessary `AUTH TLS` and STARTTLS handshake, but it all essentially comes to a halt when the `Dial` function expects a 220 response code:

```go
	_, _, err := c.conn.ReadResponse(StatusReady)
	if err != nil {
		c.Quit()
		return nil, err
	}
```
I don't think I can even poke a command at the connection after I finish the STARTTLS handshake which would leave a "220" waiting to be read.

It would be great if this package would support STARTTLS, whilst retaining the flexibility to use a cleartext data connection.

**Comment by Mynacol** [comment]
I encountered the same missing feature whilst trying to use rclone (which uses this project as a ftp client).
Are there any plans to implement this?

**Comment by heikobornholdt** [comment]
Another rclone user here. I would also like to see this feature added to this library.
