### ISSUE TITLE
Add Dial option to disable UTF8

### ISSUE THREAD

**Issue by codr7** [jlaffaye/ftp#172]
**Describe the bug**
The FTP server one of my client's ISP is using doesn't recognize the UTF8 option and refuses to continue from there. I had to comment the line in the library to get it to work. 

**To Reproduce**
```
Connect to ftpcluster.loopia.se and enable UTF8.
```

**Comment by crazy-max** [comment]
Hey bot look at #178 :robot:

**Comment by codr7** [comment]
Nice, thanks!

**Comment by crazy-max** [comment]
@jlaffaye Can you merge #178?

**Comment by crazy-max** [comment]
Up
