### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by ernado** [jlaffaye/ftp#175]
Hi! Thank you for your great project!

Please use [semantic versioning](https://semver.org/).
It is ok to start with `v0` version to allow backward incompatible changes.

This will allow users to pin specific version instead of commit hash and setup auto-updating (e.g. renovate bot).

**Comment by crazy-max** [comment]
Can't agree more!

**Comment by mef13** [comment]
+ for semver. It's simply! Only add tag like v0.1.0 to latest commit. And increment last namber for each fix commit. Or middle if commit with new feature)

**Comment by corny** [comment]
Please tag it! I agree to use `v.0.1.0` as the first tag.

**Comment by corny** [comment]
@jlaffaye ping

**Comment by blaketastic2** [comment]
@jlaffaye Any updates on this? Some organizations require a semantic version to use the code.

**Comment by worblehat** [comment]
+1
I'd love to see semantic versioning, too. Being able to select a specific version of the library to use in a project instead of just an unreadable commit hash would be really nice.

**Comment by Xuanwo** [comment]
Hello, is there any update on this issue? Maybe we can release a `v0.1.0` version at first?

**Comment by jpfluger** [comment]
For more info on pushing tags, see [here](https://git-scm.com/book/en/v2/Git-Basics-Tagging) and [here](https://stackoverflow.com/questions/5195859/how-do-you-push-a-tag-to-a-remote-repository-using-git). 

Here's a start...

```
git tag v0.1.0
git push origin v0.1.0
```

The tag should automatically appear in github.
