### ISSUE TITLE
Better docs on List and MLST/MLSD support

### ISSUE THREAD

**Issue by philips** [jlaffaye/ftp#184]
**Describe the bug**

I found it very surprising that List() was returning timestamps with an incorrect year. More digging found that the root cause was that if this library encounters an FTP server that returns timestamps without a year in the timestamp it just guesses. https://github.com/jlaffaye/ftp/blob/master/parse.go#L235

I think two things should happen and would like to send two PRs:

1. The Godoc mentions this year guessing on List and Walk
2. MLST/MLSD should be supported as an alternative format to List where supported

**To Reproduce**
```
Fun List against an rclone ftp server
```

**Expected behavior**

Dates to be set in 2019, 2018, etc

**FTP server**
- Name and version: rclone 1.52.1

**Comment by jlaffaye** [comment]
Do you have an example of an entry with a bad year ?
Its parsing the format used by `ls` on unix. If its not older than 6 months, the year if not in the output.

**Comment by philips** [comment]
My ftp server was ftp mode on rclone. I have sense moved to the sftp mode and so I am going to close this issue.
