### ISSUE TITLE
Error EOF

### ISSUE THREAD

**Issue by darlandieterich** [jlaffaye/ftp#195]
Hi! why occours the error EOF when connecting in the server?

`client, err := ftp.Dial("ftp.anotherserver.com:22")
if err != nil {
	fmt.Println(err)
}`

In my another client FTP (filezilla) I has success to connect in the server

thanks

**Comment by luistm** [comment]
Hi, 
Can you advance what was the problem in your server? I'm having a similar issue. Thank you
