### ISSUE TITLE
add PRET support

### ISSUE THREAD

**Issue by DevilStyle** [jlaffaye/ftp#197]
hi, I would like to ask a question with the ftp configuration with rclone, configuring ftp and tried to connect I get this error message, any ideas to solve it? Thank you

ERROR:: error listing: 500 You need to use a client supporting PRET (PRE Transfer) to use PASV
2020/09/08 16:24:43 Failed to lsd with 2 errors: last error was: 500 You need to use a client supporting PRET (PRE Transfer) to use PASV

**Comment by ncw** [comment]
I have a pull request pending for this which I'll send when it has been tested.

**Comment by ncw** [comment]
I have made a PR for this now #202

**Comment by ncw** [comment]
Please leave this open!
