### ISSUE TITLE
Feature: TLS session reuse

### ISSUE THREAD

**Issue by luckcolors** [jlaffaye/ftp#203]
**Describe the bug**
Attempting to use this library with a FTP server with Implicit TLS causes the error: 450 TLS session of data connection has not resumed or the session does not match the control connection.

**To Reproduce**
Use the lib as the example, error appears when attempting to upload. Follows the tls Client config that i use.
```
ftp.dialOptions = append(ftp.dialOptions, ftp.DialWithExplicitTLS(&tls.Config{
	InsecureSkipVerify: FTPTLSInsecureSkipVerify,
	ClientSessionCache: tls.NewLRUClientSessionCache(32), //not sure if this is necessary, saw this done on another FTP Client
}))
```

**Expected behavior**
The client should work and be able to upload files. I connect to the same server using WINSCP and it works there.

**FTP server**
- Filezilla (unknown version, but definetely higher than 0.9.51)
- It's unfortunately a private server, but if you have a public server i can test against i'll use that.

**Debug output**
```
PBSZ 0
200 PBSZ = 0
PROT P
200 Protection level set to P
CWD ...
250 CWD successful
EPSV
229 Entering Extended Passive Mode (|||50019|)
STOR ... //repeats for all files to upload
450 TLS session of data connection has not resumed or the session does not match the control connection. //repeats for all files to upload
QUIT
```

**Additional context**
By searching around the issue i've found this filezilla thread: https://forum.filezilla-project.org/viewtopic.php?t=36903
The issue seems to be caused by a new feature of Filezilla since version 0.9.51 that allows the server to require the client to support session resuming.

If possible i would like to fix this, or the add the feature if not already present, as i cannot edit the configuration of the remote FTP as it's production server.
I'm availble if you need other details, testing, or code.
Thanks for your time and work in making this lib. 😄

**Comment by jlaffaye** [comment]
Hello,
You're using `DialWithExplicitTLS` but you are also saying that the server is using implicit TLS.
Is the server using explicit or implicit TLS ?
