### ISSUE TITLE
How to implement FTP connection pool

### ISSUE THREAD

**Issue by cobolbaby** [jlaffaye/ftp#206]
When creating multiple coroutines to synchronize files to FTP in parallel, If only one connection is used, it may lead to the incorrect upload directory. 

So how to implement a safe and reliable connection pool?

**Comment by matiniamirhossein** [comment]
You can create workers as go routines, each worker gets their own connection.

**Comment by cobolbaby** [comment]
Have you ever seen a similar code implementation?

**Comment by jlaffaye** [comment]
Each goroutine should have its own FTP connection to avoid that.
