### ISSUE TITLE
ServerConn is hard to mock

### ISSUE THREAD

**Issue by shigmas** [jlaffaye/ftp#216]
This seems to be the best library for an FTP client. But, for my unit test, I'd like to mock it rather than making a network call.

I have only a little over a year of go under my belt, so I'm not sure if I'm testing the "right" way. But in my possibly naive approach to testing, Having interfaces over the public structs would make testing simpler. I wrote an interface with the subset of ServerConn that I'm using, but, for returning the *ftp.Response, I can't mock that, because it's not an interface. For testing, I forked, and made "Response" an interface, and "response" the concrete struct. Entry is also a candidate, but I didn't need it for my case.

Of course, having an interface that ServerConn implements would be helpful, but that's trivial to write. It's the structs that are returned by ServerConn that would make a mocking possible.

If I'm testing in a non-golang way, I'd love to be guided to a less invasive way than introducing interfaces.

**Comment by corny** [comment]
If you want to mock the ServerConn, then you have to create interfaces for all structs of this library that you are using. I suggest you to start a real FTP server instead. You could use a container environment like docker for that.

**Comment by shigmas** [comment]
I am using a container to test for my development. But, in an automated test environment like, say, github actions, spinning a container up and down adds a bit of overhead, and when it's just a small part of a large system, it's another point of failure.

Writing the layer to switch between this library and calling different test function has been much more code than it was to mock the interface for Response that I did in my fork, FWIW.
