### ISSUE TITLE
Store file got 522 SSL connection failed: session reuse required

### ISSUE THREAD

**Issue by codingXiang** [jlaffaye/ftp#223]
I want to connect FTP Server use `FTPS`, everything is fine util use `Stor` command to upload file, here is my code:

```go
package main

import (
	"bytes"
	"crypto/tls"
	"fmt"
	"github.com/jlaffaye/ftp"
	"log"
	"os"
	"time"
)

const (
	Server = "127.0.0.1"
	Port     = 990
	Username = "test"
	Password = "test"
)

func main() {
	opts := []ftp.DialOption{
		ftp.DialWithTimeout(10 * time.Second),
		ftp.DialWithTLS(&tls.Config{
			InsecureSkipVerify: true,
		}),
		ftp.DialWithDebugOutput(os.Stdout),
	}

	addr := fmt.Sprintf("%s:%d", Server, Port)

	c, err := ftp.Dial(addr, opts...)
	if err != nil {
		log.Fatal(err)
	}

	err = c.Login(Username, Password)
	if err != nil {
		log.Fatal(err)
	}


	data := bytes.NewBufferString("Hello World")
	err = c.Stor("test.txt", data)
	if err != nil {
		log.Fatal(err)
	}
}

```

log :
```log
220 (vsFTPd 3.0.3)
USER rogstmss_43
331 Please specify the password.
PASS f29bfbc
230 Login successful.
FEAT
211-Features:
 AUTH TLS
 EPRT
 EPSV
 MDTM
 PASV
 PBSZ
 PROT
 REST STREAM
 SIZE
 TVFS
211 End
TYPE I
200 Switching to Binary mode.
PBSZ 0
200 PBSZ set to 0.
PROT P
200 PROT now Private.
EPSV
229 Entering Extended Passive Mode (|||5701|)
STOR test.txt
150 Ok to send data.
522 SSL connection failed: session reuse required
2021/04/12 18:02:12 522 SSL connection failed: session reuse required
```

please help me to solve this problem, thank you !

**Comment by raidancampbell** [comment]
For pure-FTPd servers after 1.0.42 with TLS is enabled (explicit), the server will only accept reused SSL sessions by default.  This took several days to diagnose since the server didn't return or log any error, and just closed the connection most of the way through the handshake.

Since I don't see any way to support reuse client-side, passing the `-b` or `--brokenclientscompatibility` flag server-side fixed the issue for me.

**Comment by myzero1** [comment]
You should set ServerName and ClientSessionCache in tls.Config, for example:

&tls.Config{
    InsecureSkipVerify: true, // Skips certificate verification (not recommended for production)
    ServerName:         "192.168.60.131",
    ClientSessionCache: tls.NewLRUClientSessionCache(0), 
}
