### ISSUE TITLE
Last modified timestamp

### ISSUE THREAD

**Issue by bluescreen** [jlaffaye/ftp#227]
Is it possible to return the full last modified timestamp of a file including seconds?

When i use the LIST command i only get minutes in the Entry object. 
Seconds is always 00
Time:2021-06-06 17:46:00 +0000 UTC

Is there a last Modified command?

**Comment by corny** [comment]
Please paste a complete line of the LIST response. This library supports many formats, but probably not the one of your server.
See also: https://github.com/jlaffaye/ftp/blob/master/parse_test.go
