### ISSUE TITLE
Issues with PASV mode while in IPv6 session.

### ISSUE THREAD

**Issue by mmolinac** [jlaffaye/ftp#236]
**Describe the bug**
During FTP session establishment with an IPv6 connection, passive parameters are not correctly handled

**To Reproduce**
The error is reported in a `clickhouse-backup` backup session like the one [here](https://github.com/AlexAkulov/clickhouse-backup/issues/290).

```
PASV
227 Entering Passive Mode (2,233,252).
2021/10/25 19:04:48 debug FTP::returnConnectionToPool(Walk) active=1 idle=0
QUIT
2021/10/25 19:04:48 error invalid PASV response format
```

**Expected behavior**
It works like a charm if the session is IPv4.

**FTP server**
- Name and version: ProFTPD Server (no reported version).
- Public URL if applicable: u253417.your-storagebox.de

Please be aware that the DNS record has both A and AAAA entries, so in order to reproduce you have to connect with an IPv6 connection.

**Debug output**
```
N/A
```

**Additional context**
We're not using directly the library, but `clickhouse-backup` utility is the one using it.

**Comment by Slach** [comment]
@jlaffaye thanks a lot for suggesting. Look like it was external contribution, please close this issue
