### ISSUE TITLE
Stor / Retr progress indication possible?

### ISSUE THREAD

**Issue by Tobio89** [jlaffaye/ftp#247]
Hi,

I'm rebuilding an FTP program I wrote in Python in Golang.
In the Python program I have a callback that shows the progress of the transfer.
Is that possible with this library?
Thanks!

**Comment by jlaffaye** [comment]
- `Retr`: you are the one reading from the io.Reader so its a matter of sun'ing the bytes you see and divide with the total number of bytes
- `Stor`: this is trickier. I think the API should return an io.Writer.
