### ISSUE TITLE
Upload big file with Stor : 426 error code from vsftpd server

### ISSUE THREAD

**Issue by sventhommet** [jlaffaye/ftp#249]
Hi, 

**Describe the bug**

In a context of a big file (5 MB), when I try to send data using Stor() function, the server received only approx 1.000.000 to 3.000.000 bytes (not deterministic, depending on the network congestion ?) before the data connection become "unexpectedly" closed. 
Then server send a 426 error code on control connection.

**To Reproduce**
```
type FtpWriteCloser struct {
	client   *ftp.ServerConn
	fullPath string
	writer   io.WriteCloser
	reader   io.ReadCloser
	closed   bool
	mutex    sync.Mutex
	errChan  chan error
}

func (w *FtpWriteCloser) Write(p []byte) (n int, err error) {
	w.mutex.Lock()
	defer w.mutex.Unlock()

	if w.closed {
		return 0, net.ErrClosed
	}

	if w.writer == nil {
		pipeR, pipeW := io.Pipe()
		w.reader = pipeR
		w.writer = pipeW

		go func() {
			w.errChan <- w.client.Stor(w.fullPath, w.reader)
		}()

	}

	return w.writer.Write(p)
}
```

**Expected behavior**

The entire file has been uploaded to the server.

**FTP server**
- vsftpd v3.0.3

**Debug output**
```
220 (vsFTPd 3.0.3)
AUTH TLS
234 Proceed with negotiation.
USER my-user
331 Please specify the password.
PASS **********
230 Login successful.
FEAT
211-Features:
 AUTH TLS
 EPRT
 EPSV
 MDTM
 PASV
 PBSZ
 PROT
 REST STREAM
 SIZE
 TVFS
211 End
TYPE I
200 Switching to Binary mode.
PBSZ 0
200 PBSZ set to 0.
PROT P
200 PROT now Private.
NOOP
200 NOOP ok.
MKD /foo/bar/mNT8gJkLZ
257 "/foo/bar/mNT8gJkLZ" created
EPSV
229 Entering Extended Passive Mode (|||2405|)
STOR /foo/bar/mNT8gJkLZ/fatty.txt
150 Ok to send data.
426 Failure reading network stream.
```

*Server debug*

```
Wed Feb 23 15:53:41 2022 [pid 77] CONNECT: Client "::ffff:**.**.**.**"
Wed Feb 23 15:53:41 2022 [pid 76] [datastore] OK LOGIN: Client "::ffff:**.**.**.**"
Wed Feb 23 15:53:41 2022 [pid 78] [datastore] OK MKDIR: Client "::ffff:**.**.**.**", "/foo/bar/mNT8gJkLZ"
Wed Feb 23 15:53:47 2022 [pid 77] [datastore] DEBUG: Client "::ffff:**.**.**.**", "DATA connection terminated without SSL shutdown. Buggy client! Integrity of upload cannot be asserted."
Wed Feb 23 15:53:47 2022 [pid 78] [datastore] FAIL UPLOAD: Client "::ffff:**.**.**.**", "/foo/bar/mNT8gJkLZ/fatty.txt", 4472832 bytes, 699.44Kbyte/sec
```

We can see here that 4472832 out of 5242880 bytes have effectively been received by the server.

**Additional context**

I believe this maybe comes from ftp.go (l. 830)
```
	// Use io.Copy or Handshake error in preference to this one
	closeErr := conn.Close()
	if err == nil {
		err = closeErr
	}

	// Read the response and use this error in preference to
	// previous errors
	respErr := c.checkDataShut()
	if respErr != nil {
		err = respErr
	}
```
Is it possible that the data connection is closed before each bytes has been effectively received by the remote server ?
I mean, `	n, err = io.Copy(conn, r)` has copied each bytes in net.Conn buffer but the server may not have received everything when `closeErr := conn.Close()` is called ?

Thanks for your help !

**Comment by jlaffaye** [comment]
I see `PROT P` in your debug output. Are you using TLS ?

**Comment by jlaffaye** [comment]
Can you retry with fed5bc26b7fa23f7ca63998bdecc71f0d1d416af and post the error returned by the function ?

**Comment by jlaffaye** [comment]
Do you have `strict_ssl_read_eof` on the server ?

**Comment by jlaffaye** [comment]
Do you know which TLS version was used before ?
On which side (server or client) did you force TLS 1.2 ?

**Comment by cytown** [comment]
> Do you know which TLS version was used before ? On which side (server or client) did you force TLS 1.2 ?

Client side set like these:
```
tls.Config{
			InsecureSkipVerify: true,
			MinVersion:         tls.VersionTLS12,
			MaxVersion:         tls.VersionTLS12,
		}
```
