### ISSUE TITLE
Question around FEAT support

### ISSUE THREAD

**Issue by panthony** [jlaffaye/ftp#260]
**Describe the bug**

I try to access an FTP server and the client fails to detect the available features.

The server response looks like this:

```
Tx: "FEAT"
Rx: "211-Features:"
Rx: "211-CLNT"
Rx: "211-EPRT"
Rx: "211-EPSV"
Rx: "211-HOST"
Rx: "211-LANG fr-FR"
Rx: "211-MDTM"
Rx: "211-MFF modify;UNIX.group;UNIX.mode;"
Rx: "211-MFMT"
Rx: "211-MLST modify*;perm*;size*;type*;unique*;UNIX.group*;UNIX.groupname*;UNIX.mode*;UNIX.owner*;UNIX.ownername*;"
Rx: "211-RANG STREAM"
Rx: "211-REST STREAM"
Rx: "211-SITE COPY"
Rx: "211-SITE MKDIR"
Rx: "211-SITE RMDIR"
Rx: "211-SITE SYMLINK"
Rx: "211-SITE UTIME"
Rx: "211-SIZE"
Rx: "211-TVFS"
Rx: "211-UTF8"
Rx: "211 End"
```

The response does not follow "RFC 2389", I could track this notation to the following issue for ProFTPD (fixed since then):

http://bugs.proftpd.org/show_bug.cgi?id=2752

But I can't tell for sure the server I'm facing uses an old version of ProFTPD.

**Expected behavior**

I'm not sure actually, this project strictly follows the FTP specifications but at the same time there is this known bug in ProFTPD...

Ideally it may be nice to support this unfortunate output since when you work with various FTPs you do not always have a choice.

I can't really ask every impacted users to upgrade their FTP server.

**Context**

The feature detection is used to enables the efficient lookup (https://github.com/jlaffaye/ftp/pull/258)

**Comment by jlaffaye** [comment]
The fix is in upstream since 2006 ? I say we dont have to work around the bug then.
