### ISSUE TITLE
short response" errors from at least one FTP Server

### ISSUE THREAD

**Issue by dhait** [jlaffaye/ftp#267]
CrushFTP and some other servers, in response to a FEAT command, prefix each feature with a " ".  This is giving "short response" warnings.  Example (CrushFTP):

```
211-Extensions supported:
 AUTH TLS
 AUTH SSL
 SSCN
 PBSZ
 PROT
 CCC
 CLNT
 EPSV
 EPRT
 MDTM
 MDTM YYYYMMDDHHMMSS[+-TZ];filename
 MFMT
 SIZE
 REST STREAM
 MODE Z
 LIST -Q
 SITE UTIME
 SITE MD5
 XMD5
 SITE MD5s
 SITE RANDOMACCESS
 MLST Type*;Size*;Modify*;Perm*;UNIX.owner*;UNIX.group*;
 UTF8
211 END
```

Might I suggest a solution could be to trim initial spaces from the FTP server response lines?

**Comment by jlaffaye** [comment]
What's the real issue here ?
We already trim the lines (https://github.com/jlaffaye/ftp/blob/master/ftp.go#L409)

**Comment by dhait** [comment]
Sorry, I can't seem to reproduce this.  My mistake - I'm closing it out.
