### ISSUE TITLE
Add configurable timeout

### ISSUE THREAD

**Issue by claudiofelber** [jlaffaye/ftp#27]
What about adding a possibility to specify a connection timeout. This would be quite easy to do by internally using `textproto.NewConn()` instead of `textproto.Dial()`. To keep the API stable you might want to add a second Connect function like the following:

```
func ConnectTimeout(addr string, timeout time.Duration) (*ServerConn, error) {
    _conn, err := net.DialTimeout("tcp", addr, timeout)
    if err != nil {
        return nil, err
    }

    conn := textproto.NewConn(_conn)
    ...
}
```

Maybe it would be better to use `Dial()` and `DialTimeout()` instead of `Connect()` and `ConnectTimeout()` in order to stay compatible with the rest of the Go standard library.

**Comment by boomlinde** [comment]
Hi, I just did this work with PR #28 without reading the issues first :)
