### ISSUE TITLE
Active Mode not supported

### ISSUE THREAD

**Issue by d2g** [jlaffaye/ftp#29]
Hi,

Can you confirm that active mode is not supported?

Will it be supported in the future?

**Comment by jlaffaye** [comment]
Yes, active mode is not supported.
Mainly because everyone prefer passive mode over active mode.
What is the use case of active mode ?

**Comment by d2g** [comment]
An existing service uses active mode and passive mode doesn't function. I think it might be an old windows ftp service where it's not implemented (I'm not responsible for the server, just the client).

**Comment by CodyGuo** [comment]
HI,
Can support active mode in the future?
Our server only open the ports 21, so can only choose to active mode.
Thank you very much!

**Comment by corny** [comment]
Feel free to implement :)

**Comment by AlekSi** [comment]
:+1:
