### ISSUE TITLE
FTP Client Error Codes/Messages

### ISSUE THREAD

**Issue by stevebail** [jlaffaye/ftp#295]
What are the status codes or error messages supported by the FTP client?
The FTP reply codes are specified for FTP server side (as per RFC), but client codes/messages are missing as far as I know.
Did I miss something?
How does the client behave when connection attempt fails, or when it has received an error message in a reply?
Any help would be greatly appreciated.

**Comment by jlaffaye** [comment]
>client codes/messages are missing as far as I know.

what do you mean ?
