### ISSUE TITLE
can't create directory like linux "mkdir -p" 

### ISSUE THREAD

**Issue by lazywhite** [jlaffaye/ftp#332]
my environment
ftp server: vsftp
ftp client: lftp

I can use lftp to do "mkdir -p" successfully, but can't do it by this method, what's the problem?   
Does "mkdir -p" is implemented by client side,  not server side?
```
func (c *ServerConn) MakeDirs(path string) error {
	_, _, err := c.cmd(StatusPathCreated, "MKD -p %s", path)   // I add  "-p" parameter here
	return err
}
```

**Comment by jlaffaye** [comment]
Yes, you have to call https://pkg.go.dev/github.com/jlaffaye/ftp#ServerConn.MakeDir recursively.
