### ISSUE TITLE
How to overwrite file when I called `Stor` method?

### ISSUE THREAD

**Issue by yudidi** [jlaffaye/ftp#358]
**Describe the bug**

**To Reproduce**
```
Please include a mininal test case as code
```

**Expected behavior**

**FTP server**
- Name and version:
- Public URL if applicable

**Debug output**
```
Please include the ouput generated via DialWithDebugOuput
```

**Additional context**
User Linux and windows ftp both.

**Comment by jlaffaye** [comment]
can you try https://pkg.go.dev/github.com/jlaffaye/ftp#ServerConn.StorFrom with an offset of 0 ?
