### ISSUE TITLE
Unable to get directory list

### ISSUE THREAD

**Issue by zlepper** [jlaffaye/ftp#56]
```
func doesDirectoryExist(f *ftp.ServerConn, dir string) bool {
    entries, err := f.NameList("")
    if err != nil {
        panic(err)
    }
        // Some more stuff that checks if the directory exists
}
```

When I run that piece of code against my microsoft ftp server, it panics with the following message:
`dial tcp 80.197.32.208:55684: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

Before the doesDirectoryExist function is called i have run both Connect, Login and ChangeDir. 

Everything works perfect when i connect to a filezilla ftp server. 
I can also connect to the microsoft ftp server using filezilla client without issues. 
I have tried with both the List and NameList functions.

**Comment by jlaffaye** [comment]
do you have a public microsoft ftp server, so I can debug ?

**Comment by zlepper** [comment]
Url: `zlepper.dk`
Username: `debug`
Password: `mHB5't?1-.AZ2R-i|5z0l~eZzrcuD6U?`

The user only had read access to prevent damage. And there is nothing on that server that is private as it has directory browsing enable from the website, so you can see [here](http://zlepper.dk/) if the listings match.

**Comment by zlepper** [comment]
Did you fix the issue since this was closed?
