### ISSUE TITLE
Entry.Size format?

### ISSUE THREAD

**Issue by Lempiraholio** [jlaffaye/ftp#57]
The size of an entry is uint64, but what does it represent? B, KB, MB?

**Comment by corny** [comment]
The size is in bytes.

**Comment by Lempiraholio** [comment]
Thank you!

**Comment by shurcooL** [comment]
Should that be added to the documentation, or is it unnecessary because it's clear that it's bytes as is?

**Comment by Lempiraholio** [comment]
Hello, @shurcooL 

I think it should be added to the documentation, I think it's clear that the size is in bytes, but I think it would be better for people that are in doubt. Thank you!
