### ISSUE TITLE
Strage error while stor to ftp server

### ISSUE THREAD

**Issue by AnotherGoogleFan** [jlaffaye/ftp#61]
I connect and login successfully. But while I try to Stor, I receive strange errors like this:

229 Entering Extended Passive Mode (|||30005|)
short response:  SITE PSWD;SET;ZONE;CHMOD;MSG;EXEC;HELP
short response:  AUTH TLS;SSL;TLS-C;TLS-P;

**Comment by jlaffaye** [comment]
What is the software of the remote FTP server ?
If you dont know, what is the URL ?

**Comment by AnotherGoogleFan** [comment]
@jlaffaye Sorry, it's my fault. I use goroutine in a wrong way.
