### ISSUE TITLE
when call ftp.Connect ,the error  returned is not nil in  some net environment 

### ISSUE THREAD

**Issue by kekemuyu** [jlaffaye/ftp#68]
when call ftp.Connect ,the error  returned is not nil in  some net environment .But others ftp clients like winscp works well in the same net enviroment. somebody can tell me the reason?

**Comment by corny** [comment]
Just print the error an you get the answer.

**Comment by kekemuyu** [comment]
the error is :
wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by corny** [comment]
So ask microsoft or use [wireshark](https://www.wireshark.org/) for further debugging. It's not a problem of this library.

**Comment by kekemuyu** [comment]
But winscp works well in the same pc.

**Comment by kekemuyu** [comment]
And  if I change a wifi ,the ftp also wroks well.The bug is hard to debug for me.

**Comment by jlaffaye** [comment]
Is really a FTP server or a SSH (SCP) server ? WinSCP can do both.

**Comment by jlaffaye** [comment]
No data to reproduce the issue.
