### ISSUE TITLE
Allow setting a read timeout on data connection

### ISSUE THREAD

**Issue by kjk** [jlaffaye/ftp#70]
I'm using this library for some heavy-duty ftp'ing (hundreds of gigabytes transferred).

I observed that sometimes transfer hangs (I use `io.Copy()` on ftp reader to a destination file reader). My theory is that Read() never completes.

A `Read()` just goes to underlying tcp connection's `Read`. The hang makes sense given that a default Read timeout is infinite so if a server I'm trying to read from never sends me data, my program will hang forever.

It's possible to set a timeout on tcp connection with `SetDeadline/SetReadDeadline` but as far as I can tell there's no way to set it on a io.ReadCloser returned from ServerConn.Retr().

There are 2 basic ways of allowing it:
* add a way to grab underlying net.Conn connection (so that the caller can call SetDeadline etc. as needed)
* change returned value to an interface that is a superset of io.ReadCloser which also includes SetDeadline, SetReadDeadline, SetWriteDeadline, which would proxy to underlying net.Conn

First solution is less invasive and more future-proof but both of them require changing the type of value returned from Retr (and Store etc.). It should be backwards-compatible as long as that type is a superset of io.ReadCloser.

**Comment by kjk** [comment]
And for good measure when the library calls read internally (for e.g. ServerConn.List), it should use some reasonable timeout as well.

**Comment by corny** [comment]
Since there are continously created new connections it is not enough to just set deadlines for the control connection. Is it fine to set deadlines for all connections of a client instance?

**Comment by corny** [comment]
That change was super easy.
