### ISSUE TITLE
FTP returned err `Please log in with USER and PASS first`  on set UTF command

### ISSUE THREAD

**Issue by rudbast** [jlaffaye/ftp#72]
I have some issues on this commit 5a8b8eeb129259bccb909543ddb7f72d093ec2a1

I'm not sure if it's to be expected or anything, but I'm not able to connect the FTP server past this commit.
The error message was `Please log in with USER and PASS first`.

The server is using FileZilla Server version 0.9.33 beta, I'm not sure if it's because a bug in the current FTP server version, haven't found any reference to it.

I tried the commit prior to that, and it works fine.

**Comment by corny** [comment]
Please try #73

**Comment by rudbast** [comment]
Hi @corny, yeah it works fine now with #73. Nice :+1:
