### ISSUE TITLE
determine if directory already exists

### ISSUE THREAD

**Issue by mappu** [jlaffaye/ftp#78]
Hi,

I want to check if a directory already exists on the FTP server.

One possibility is to `List()` the directory. But this might be slow if there are a lot of entries.

I think `Stat()` might only work on files (or maybe i'm wrong, does it also works on directories?)

The remaining idea is to try `Mkdir()` it and test for `450` response. But, this library does not expose the code response from `Mkdir()`. I think Mkdir() should return a new ErrAlreadyExist when encountering a 450 response. Then, upstream code can detect whether the directory already exists on the FTP server.

Thanks,
~mappu

**Comment by mappu** [comment]
I mean `550` not `450`.

This kind of patch works for me:

```diff -r 07064622aeac gopath/src/vendor/github.com/jlaffaye/ftp/ftp.go
--- a/gopath/src/vendor/github.com/jlaffaye/ftp/ftp.go	Fri Mar 03 09:34:55 2017 +1300
+++ b/gopath/src/vendor/github.com/jlaffaye/ftp/ftp.go	Fri Mar 03 09:59:01 2017 +1300
@@ -492,10 +492,18 @@
 	return err
 }
 
+var ErrDirAlreadyExists = errors.New("Directory already exists")
+
 // MakeDir issues a MKD FTP command to create the specified directory on the
 // remote FTP server.
 func (c *ServerConn) MakeDir(path string) error {
-	_, _, err := c.cmd(StatusPathCreated, "MKD %s", path)
+	code, _, err := c.cmd(StatusPathCreated, "MKD %s", path)
+
+	// The upstream server will return code 550 if the directory already exists.
+	if code == StatusFileUnavailable {
+		return ErrDirAlreadyExists
+	}
+
 	return err
 }
```

But, maybe a broader-patch would convert all the 4xx/5xx status codes into corresponding Err constants for specific testing.

**Comment by mappu** [comment]
Actually i'm not so happy about this kind of patch, because it mixes up "directory already exists" with other errors (e.g. 550 mkdir failed because of permission issues). But it would still be useful to distinguish between coded 550 responses and other types of FTP errors / network errors in responses.

**Comment by shurcooL** [comment]
Could [`os.ErrExist`](https://godoc.org/os#ErrExist) be relevant here?

There's also [`os.IsExist`](https://godoc.org/os#IsExist) that can recognize it.

**Comment by jlaffaye** [comment]
I just added a comment so users know that they can use type assertion on textproto.Error to get the real ftp error
