### ISSUE TITLE
Connection impossible behind proxy

### ISSUE THREAD

**Issue by BertrandD** [jlaffaye/ftp#86]
I can't establish a connection on a ftp server if my system is behind a proxy

`
ftp.DialTimeout("ftp.mydomain.com:21")
`

The code is blocking here and waiting it ends with a `dial tcp 11.11.11.11:21: getsockopt: connection timed out`

Where `11.11.11.11` is the ip of `ftp.mydomain.com`, not accessible without proxy...

My proxy settings are available in environment variables (HTTP_PROXY, FTP_PROXY, http_proxy, ftp_proxy)

**Comment by jlaffaye** [comment]
Could now be implement with custom dialer (DialWithOptions)
