### ISSUE TITLE
Login Method shouldn't switch to UTF-8 automatically

### ISSUE THREAD

**Issue by warrenbailey** [jlaffaye/ftp#89]
The login method attempts to switch to UTF-8 immediately after a successful login. However I'm working with a server that doesn't support the OPTS UTF8 ON command and therefore I always get an error back from the Login method even though I can still send/retrieve files.

It also automatically sets the connection to binary mode. I'd argue that both these options shouldn't be part of the login method and it should be left to the client code to decide if it wants them.

**Comment by corny** [comment]
> I'm working with a server that doesn't support the OPTS UTF8 ON

Why does the server offer the `UTF8` command if it does not support it? Sounds broken for me.
