### ISSUE TITLE
When fetching data,we met a problem with error code 229

### ISSUE THREAD

**Issue by hailong0715** [jlaffaye/ftp#95]
hi 
can somebody help me clarify this issue?
we use jlaffaye/ftp to build a ftp client.
but after using Dial() & Login() function to build a connection with remote FTP server,we tried to fectch data with Retr() function，this function returned with error code 229（229 Entering Extended Passive Mode (|||38785|)），how does this happen？ and how can we solve this?
Great thanks

**Comment by hailong0715** [comment]
issue closed. For responseReader is not been closed.

**Comment by dominhtri1995** [comment]
Hi , how did you resolve the problem ? Not sure what is responseReader ?  I got this error the moment I call:

		r, err := c.Retr(myPath)
